/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IConfigurable {
  export type TokenConfigStruct = {
    minMarginPerLiquidityPosition: PromiseOrValue<BigNumberish>;
    maxRiskRatePerLiquidityPosition: PromiseOrValue<BigNumberish>;
    maxLeveragePerLiquidityPosition: PromiseOrValue<BigNumberish>;
    minMarginPerPosition: PromiseOrValue<BigNumberish>;
    maxLeveragePerPosition: PromiseOrValue<BigNumberish>;
    liquidationFeeRatePerPosition: PromiseOrValue<BigNumberish>;
    liquidationExecutionFee: PromiseOrValue<BigNumberish>;
    interestRate: PromiseOrValue<BigNumberish>;
    maxFundingRate: PromiseOrValue<BigNumberish>;
  };

  export type TokenConfigStructOutput = [
    BigNumber,
    number,
    number,
    BigNumber,
    number,
    number,
    BigNumber,
    number,
    number
  ] & {
    minMarginPerLiquidityPosition: BigNumber;
    maxRiskRatePerLiquidityPosition: number;
    maxLeveragePerLiquidityPosition: number;
    minMarginPerPosition: BigNumber;
    maxLeveragePerPosition: number;
    liquidationFeeRatePerPosition: number;
    liquidationExecutionFee: BigNumber;
    interestRate: number;
    maxFundingRate: number;
  };

  export type TokenFeeRateConfigStruct = {
    tradingFeeRate: PromiseOrValue<BigNumberish>;
    liquidityFeeRate: PromiseOrValue<BigNumberish>;
    protocolFeeRate: PromiseOrValue<BigNumberish>;
    referralReturnFeeRate: PromiseOrValue<BigNumberish>;
    referralParentReturnFeeRate: PromiseOrValue<BigNumberish>;
    referralDiscountRate: PromiseOrValue<BigNumberish>;
  };

  export type TokenFeeRateConfigStructOutput = [
    number,
    number,
    number,
    number,
    number,
    number
  ] & {
    tradingFeeRate: number;
    liquidityFeeRate: number;
    protocolFeeRate: number;
    referralReturnFeeRate: number;
    referralParentReturnFeeRate: number;
    referralDiscountRate: number;
  };

  export type VertexConfigStruct = {
    balanceRate: PromiseOrValue<BigNumberish>;
    premiumRate: PromiseOrValue<BigNumberish>;
  };

  export type VertexConfigStructOutput = [number, number] & {
    balanceRate: number;
    premiumRate: number;
  };

  export type TokenPriceConfigStruct = {
    maxPriceImpactLiquidity: PromiseOrValue<BigNumberish>;
    liquidationVertexIndex: PromiseOrValue<BigNumberish>;
    vertices: IConfigurable.VertexConfigStruct[];
  };

  export type TokenPriceConfigStructOutput = [
    BigNumber,
    number,
    IConfigurable.VertexConfigStructOutput[]
  ] & {
    maxPriceImpactLiquidity: BigNumber;
    liquidationVertexIndex: number;
    vertices: IConfigurable.VertexConfigStructOutput[];
  };
}

export interface PoolFactoryInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "EFC()": FunctionFragment;
    "USD()": FunctionFragment;
    "acceptGov()": FunctionFragment;
    "callback()": FunctionFragment;
    "changeGov(address)": FunctionFragment;
    "concatPoolCreationCode(bool,bytes)": FunctionFragment;
    "createPool(address)": FunctionFragment;
    "creationCode()": FunctionFragment;
    "creationCodeHash()": FunctionFragment;
    "deployParameters()": FunctionFragment;
    "enableToken(address,(uint64,uint32,uint32,uint64,uint32,uint32,uint64,uint32,uint32),(uint32,uint32,uint32,uint32,uint32,uint32),(uint128,uint8,(uint32,uint32)[]))": FunctionFragment;
    "feeDistributor()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "gov()": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isEnabledToken(address)": FunctionFragment;
    "isPool(address)": FunctionFragment;
    "pendingGov()": FunctionFragment;
    "pools(address)": FunctionFragment;
    "priceFeed()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "router()": FunctionFragment;
    "setPriceFeed(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tokenConfigs(address)": FunctionFragment;
    "tokenFeeRateConfigs(address)": FunctionFragment;
    "tokenPriceConfigs(address)": FunctionFragment;
    "tokenPriceVertexConfigs(address,uint8)": FunctionFragment;
    "updateTokenConfig(address,(uint64,uint32,uint32,uint64,uint32,uint32,uint64,uint32,uint32),(uint32,uint32,uint32,uint32,uint32,uint32),(uint128,uint8,(uint32,uint32)[]))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "EFC"
      | "USD"
      | "acceptGov"
      | "callback"
      | "changeGov"
      | "concatPoolCreationCode"
      | "createPool"
      | "creationCode"
      | "creationCodeHash"
      | "deployParameters"
      | "enableToken"
      | "feeDistributor"
      | "getRoleAdmin"
      | "gov"
      | "grantRole"
      | "hasRole"
      | "isEnabledToken"
      | "isPool"
      | "pendingGov"
      | "pools"
      | "priceFeed"
      | "renounceRole"
      | "revokeRole"
      | "router"
      | "setPriceFeed"
      | "supportsInterface"
      | "tokenConfigs"
      | "tokenFeeRateConfigs"
      | "tokenPriceConfigs"
      | "tokenPriceVertexConfigs"
      | "updateTokenConfig"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EFC", values?: undefined): string;
  encodeFunctionData(functionFragment: "USD", values?: undefined): string;
  encodeFunctionData(functionFragment: "acceptGov", values?: undefined): string;
  encodeFunctionData(functionFragment: "callback", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeGov",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "concatPoolCreationCode",
    values: [PromiseOrValue<boolean>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "creationCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creationCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployParameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableToken",
    values: [
      PromiseOrValue<string>,
      IConfigurable.TokenConfigStruct,
      IConfigurable.TokenFeeRateConfigStruct,
      IConfigurable.TokenPriceConfigStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feeDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isEnabledToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isPool",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingGov",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pools",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPriceFeed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenConfigs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenFeeRateConfigs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceConfigs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPriceVertexConfigs",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenConfig",
    values: [
      PromiseOrValue<string>,
      IConfigurable.TokenConfigStruct,
      IConfigurable.TokenFeeRateConfigStruct,
      IConfigurable.TokenPriceConfigStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EFC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptGov", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callback", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "changeGov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "concatPoolCreationCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creationCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEnabledToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingGov", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenFeeRateConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenPriceVertexConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenConfig",
    data: BytesLike
  ): Result;

  events: {
    "ChangeGovStarted(address,address)": EventFragment;
    "GovChanged(address,address)": EventFragment;
    "PoolCreated(address,address,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TokenConfigChanged(address,tuple,tuple,tuple)": EventFragment;
    "USDEnabled(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangeGovStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenConfigChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "USDEnabled"): EventFragment;
}

export interface ChangeGovStartedEventObject {
  previousGov: string;
  newGov: string;
}
export type ChangeGovStartedEvent = TypedEvent<
  [string, string],
  ChangeGovStartedEventObject
>;

export type ChangeGovStartedEventFilter =
  TypedEventFilter<ChangeGovStartedEvent>;

export interface GovChangedEventObject {
  previousGov: string;
  newGov: string;
}
export type GovChangedEvent = TypedEvent<
  [string, string],
  GovChangedEventObject
>;

export type GovChangedEventFilter = TypedEventFilter<GovChangedEvent>;

export interface PoolCreatedEventObject {
  pool: string;
  token: string;
  usd: string;
}
export type PoolCreatedEvent = TypedEvent<
  [string, string, string],
  PoolCreatedEventObject
>;

export type PoolCreatedEventFilter = TypedEventFilter<PoolCreatedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface TokenConfigChangedEventObject {
  token: string;
  newCfg: IConfigurable.TokenConfigStructOutput;
  newFeeRateCfg: IConfigurable.TokenFeeRateConfigStructOutput;
  newPriceCfg: IConfigurable.TokenPriceConfigStructOutput;
}
export type TokenConfigChangedEvent = TypedEvent<
  [
    string,
    IConfigurable.TokenConfigStructOutput,
    IConfigurable.TokenFeeRateConfigStructOutput,
    IConfigurable.TokenPriceConfigStructOutput
  ],
  TokenConfigChangedEventObject
>;

export type TokenConfigChangedEventFilter =
  TypedEventFilter<TokenConfigChangedEvent>;

export interface USDEnabledEventObject {
  usd: string;
}
export type USDEnabledEvent = TypedEvent<[string], USDEnabledEventObject>;

export type USDEnabledEventFilter = TypedEventFilter<USDEnabledEvent>;

export interface PoolFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    EFC(overrides?: CallOverrides): Promise<[string]>;

    USD(overrides?: CallOverrides): Promise<[string]>;

    acceptGov(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    callback(overrides?: CallOverrides): Promise<[string]>;

    changeGov(
      _newGov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    concatPoolCreationCode(
      _lastCreationCodePart: PromiseOrValue<boolean>,
      _creationCodePart: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createPool(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creationCode(overrides?: CallOverrides): Promise<[string]>;

    creationCodeHash(overrides?: CallOverrides): Promise<[string]>;

    deployParameters(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        _token: string;
        _usd: string;
        _router: string;
        _feeDistributor: string;
        _EFC: string;
        _callback: string;
      }
    >;

    enableToken(
      _token: PromiseOrValue<string>,
      _cfg: IConfigurable.TokenConfigStruct,
      _feeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _priceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeDistributor(overrides?: CallOverrides): Promise<[string]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    gov(overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isEnabledToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPool(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    pendingGov(overrides?: CallOverrides): Promise<[string]>;

    pools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    priceFeed(overrides?: CallOverrides): Promise<[string]>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    router(overrides?: CallOverrides): Promise<[string]>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tokenConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        number,
        number,
        BigNumber,
        number,
        number,
        BigNumber,
        number,
        number
      ] & {
        minMarginPerLiquidityPosition: BigNumber;
        maxRiskRatePerLiquidityPosition: number;
        maxLeveragePerLiquidityPosition: number;
        minMarginPerPosition: BigNumber;
        maxLeveragePerPosition: number;
        liquidationFeeRatePerPosition: number;
        liquidationExecutionFee: BigNumber;
        interestRate: number;
        maxFundingRate: number;
      }
    >;

    tokenFeeRateConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number] & {
        tradingFeeRate: number;
        liquidityFeeRate: number;
        protocolFeeRate: number;
        referralReturnFeeRate: number;
        referralParentReturnFeeRate: number;
        referralDiscountRate: number;
      }
    >;

    tokenPriceConfigs(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & {
        maxPriceImpactLiquidity: BigNumber;
        liquidationVertexIndex: number;
      }
    >;

    tokenPriceVertexConfigs(
      _token: PromiseOrValue<string>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, number] & { balanceRate: number; premiumRate: number }>;

    updateTokenConfig(
      _token: PromiseOrValue<string>,
      _newCfg: IConfigurable.TokenConfigStruct,
      _newFeeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _newPriceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  EFC(overrides?: CallOverrides): Promise<string>;

  USD(overrides?: CallOverrides): Promise<string>;

  acceptGov(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callback(overrides?: CallOverrides): Promise<string>;

  changeGov(
    _newGov: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  concatPoolCreationCode(
    _lastCreationCodePart: PromiseOrValue<boolean>,
    _creationCodePart: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createPool(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creationCode(overrides?: CallOverrides): Promise<string>;

  creationCodeHash(overrides?: CallOverrides): Promise<string>;

  deployParameters(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string, string] & {
      _token: string;
      _usd: string;
      _router: string;
      _feeDistributor: string;
      _EFC: string;
      _callback: string;
    }
  >;

  enableToken(
    _token: PromiseOrValue<string>,
    _cfg: IConfigurable.TokenConfigStruct,
    _feeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
    _priceCfg: IConfigurable.TokenPriceConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeDistributor(overrides?: CallOverrides): Promise<string>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  gov(overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isEnabledToken(
    _token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isPool(
    _pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  pendingGov(overrides?: CallOverrides): Promise<string>;

  pools(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  priceFeed(overrides?: CallOverrides): Promise<string>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  router(overrides?: CallOverrides): Promise<string>;

  setPriceFeed(
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokenConfigs(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      number,
      number,
      BigNumber,
      number,
      number,
      BigNumber,
      number,
      number
    ] & {
      minMarginPerLiquidityPosition: BigNumber;
      maxRiskRatePerLiquidityPosition: number;
      maxLeveragePerLiquidityPosition: number;
      minMarginPerPosition: BigNumber;
      maxLeveragePerPosition: number;
      liquidationFeeRatePerPosition: number;
      liquidationExecutionFee: BigNumber;
      interestRate: number;
      maxFundingRate: number;
    }
  >;

  tokenFeeRateConfigs(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number, number, number, number] & {
      tradingFeeRate: number;
      liquidityFeeRate: number;
      protocolFeeRate: number;
      referralReturnFeeRate: number;
      referralParentReturnFeeRate: number;
      referralDiscountRate: number;
    }
  >;

  tokenPriceConfigs(
    _token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number] & {
      maxPriceImpactLiquidity: BigNumber;
      liquidationVertexIndex: number;
    }
  >;

  tokenPriceVertexConfigs(
    _token: PromiseOrValue<string>,
    _index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[number, number] & { balanceRate: number; premiumRate: number }>;

  updateTokenConfig(
    _token: PromiseOrValue<string>,
    _newCfg: IConfigurable.TokenConfigStruct,
    _newFeeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
    _newPriceCfg: IConfigurable.TokenPriceConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    EFC(overrides?: CallOverrides): Promise<string>;

    USD(overrides?: CallOverrides): Promise<string>;

    acceptGov(overrides?: CallOverrides): Promise<void>;

    callback(overrides?: CallOverrides): Promise<string>;

    changeGov(
      _newGov: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    concatPoolCreationCode(
      _lastCreationCodePart: PromiseOrValue<boolean>,
      _creationCodePart: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    createPool(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    creationCode(overrides?: CallOverrides): Promise<string>;

    creationCodeHash(overrides?: CallOverrides): Promise<string>;

    deployParameters(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string, string] & {
        _token: string;
        _usd: string;
        _router: string;
        _feeDistributor: string;
        _EFC: string;
        _callback: string;
      }
    >;

    enableToken(
      _token: PromiseOrValue<string>,
      _cfg: IConfigurable.TokenConfigStruct,
      _feeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _priceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    feeDistributor(overrides?: CallOverrides): Promise<string>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    gov(overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isEnabledToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPool(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pendingGov(overrides?: CallOverrides): Promise<string>;

    pools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    priceFeed(overrides?: CallOverrides): Promise<string>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    router(overrides?: CallOverrides): Promise<string>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        number,
        number,
        BigNumber,
        number,
        number,
        BigNumber,
        number,
        number
      ] & {
        minMarginPerLiquidityPosition: BigNumber;
        maxRiskRatePerLiquidityPosition: number;
        maxLeveragePerLiquidityPosition: number;
        minMarginPerPosition: BigNumber;
        maxLeveragePerPosition: number;
        liquidationFeeRatePerPosition: number;
        liquidationExecutionFee: BigNumber;
        interestRate: number;
        maxFundingRate: number;
      }
    >;

    tokenFeeRateConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number, number, number, number] & {
        tradingFeeRate: number;
        liquidityFeeRate: number;
        protocolFeeRate: number;
        referralReturnFeeRate: number;
        referralParentReturnFeeRate: number;
        referralDiscountRate: number;
      }
    >;

    tokenPriceConfigs(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number] & {
        maxPriceImpactLiquidity: BigNumber;
        liquidationVertexIndex: number;
      }
    >;

    tokenPriceVertexConfigs(
      _token: PromiseOrValue<string>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, number] & { balanceRate: number; premiumRate: number }>;

    updateTokenConfig(
      _token: PromiseOrValue<string>,
      _newCfg: IConfigurable.TokenConfigStruct,
      _newFeeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _newPriceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ChangeGovStarted(address,address)"(
      previousGov?: PromiseOrValue<string> | null,
      newGov?: PromiseOrValue<string> | null
    ): ChangeGovStartedEventFilter;
    ChangeGovStarted(
      previousGov?: PromiseOrValue<string> | null,
      newGov?: PromiseOrValue<string> | null
    ): ChangeGovStartedEventFilter;

    "GovChanged(address,address)"(
      previousGov?: PromiseOrValue<string> | null,
      newGov?: PromiseOrValue<string> | null
    ): GovChangedEventFilter;
    GovChanged(
      previousGov?: PromiseOrValue<string> | null,
      newGov?: PromiseOrValue<string> | null
    ): GovChangedEventFilter;

    "PoolCreated(address,address,address)"(
      pool?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      usd?: PromiseOrValue<string> | null
    ): PoolCreatedEventFilter;
    PoolCreated(
      pool?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      usd?: PromiseOrValue<string> | null
    ): PoolCreatedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "TokenConfigChanged(address,tuple,tuple,tuple)"(
      token?: PromiseOrValue<string> | null,
      newCfg?: null,
      newFeeRateCfg?: null,
      newPriceCfg?: null
    ): TokenConfigChangedEventFilter;
    TokenConfigChanged(
      token?: PromiseOrValue<string> | null,
      newCfg?: null,
      newFeeRateCfg?: null,
      newPriceCfg?: null
    ): TokenConfigChangedEventFilter;

    "USDEnabled(address)"(
      usd?: PromiseOrValue<string> | null
    ): USDEnabledEventFilter;
    USDEnabled(usd?: PromiseOrValue<string> | null): USDEnabledEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    EFC(overrides?: CallOverrides): Promise<BigNumber>;

    USD(overrides?: CallOverrides): Promise<BigNumber>;

    acceptGov(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    callback(overrides?: CallOverrides): Promise<BigNumber>;

    changeGov(
      _newGov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    concatPoolCreationCode(
      _lastCreationCodePart: PromiseOrValue<boolean>,
      _creationCodePart: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createPool(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creationCode(overrides?: CallOverrides): Promise<BigNumber>;

    creationCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    deployParameters(overrides?: CallOverrides): Promise<BigNumber>;

    enableToken(
      _token: PromiseOrValue<string>,
      _cfg: IConfigurable.TokenConfigStruct,
      _feeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _priceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isEnabledToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPool(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingGov(overrides?: CallOverrides): Promise<BigNumber>;

    pools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    priceFeed(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenFeeRateConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceConfigs(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenPriceVertexConfigs(
      _token: PromiseOrValue<string>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateTokenConfig(
      _token: PromiseOrValue<string>,
      _newCfg: IConfigurable.TokenConfigStruct,
      _newFeeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _newPriceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EFC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    USD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptGov(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    callback(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeGov(
      _newGov: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    concatPoolCreationCode(
      _lastCreationCodePart: PromiseOrValue<boolean>,
      _creationCodePart: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createPool(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creationCode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creationCodeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployParameters(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enableToken(
      _token: PromiseOrValue<string>,
      _cfg: IConfigurable.TokenConfigStruct,
      _feeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _priceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeDistributor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isEnabledToken(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPool(
      _pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingGov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceFeed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setPriceFeed(
      _priceFeed: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenFeeRateConfigs(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenPriceConfigs(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenPriceVertexConfigs(
      _token: PromiseOrValue<string>,
      _index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateTokenConfig(
      _token: PromiseOrValue<string>,
      _newCfg: IConfigurable.TokenConfigStruct,
      _newFeeRateCfg: IConfigurable.TokenFeeRateConfigStruct,
      _newPriceCfg: IConfigurable.TokenPriceConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
