/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPositionRouterState,
  IPositionRouterStateInterface,
} from "../../../../contracts/misc/ExecutorAssistant.sol/IPositionRouterState";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "expiredAt",
        type: "uint256",
      },
    ],
    name: "Expired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "available",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "required",
        type: "uint256",
      },
    ],
    name: "InsufficientExecutionFee",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint160",
        name: "tradePriceX96",
        type: "uint160",
      },
      {
        internalType: "uint160",
        name: "acceptableTradePriceX96",
        type: "uint160",
      },
    ],
    name: "InvalidTradePrice",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "earliest",
        type: "uint256",
      },
    ],
    name: "TooEarly",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "AdjustLiquidityPositionMarginCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "positionID",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "int128",
        name: "marginDelta",
        type: "int128",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "AdjustLiquidityPositionMarginCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "AdjustLiquidityPositionMarginExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "CloseLiquidityPositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "positionID",
        type: "uint96",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "CloseLiquidityPositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "CloseLiquidityPositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "DecreasePositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "Side",
        name: "side",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "marginDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "sizeDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint160",
        name: "acceptableTradePriceX96",
        type: "uint160",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "DecreasePositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "DecreasePositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "DecreaseRiskBufferFundPositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidityDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "DecreaseRiskBufferFundPositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "DecreaseRiskBufferFundPositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "minBlockDelayExecutor",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "minTimeDelayPublic",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "maxTimeDelay",
        type: "uint32",
      },
    ],
    name: "DelayValuesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "IncreasePositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "Side",
        name: "side",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "marginDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "sizeDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint160",
        name: "acceptableTradePriceX96",
        type: "uint160",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "IncreasePositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "IncreasePositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "IncreaseRiskBufferFundPositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidityDelta",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "IncreaseRiskBufferFundPositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "IncreaseRiskBufferFundPositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "minExecutionFee",
        type: "uint256",
      },
    ],
    name: "MinExecutionFeeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "OpenLiquidityPositionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "margin",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "executionFee",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "OpenLiquidityPositionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "OpenLiquidityPositionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "PositionExecutorUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "adjustLiquidityPositionMarginIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adjustLiquidityPositionMarginIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "adjustLiquidityPositionMarginRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "positionID",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "int128",
            name: "marginDelta",
            type: "int128",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "receiver",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType:
          "struct IPositionRouter.AdjustLiquidityPositionMarginRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelAdjustLiquidityPositionMargin",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelCloseLiquidityPosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelDecreasePosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelDecreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelIncreasePosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelIncreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "cancelOpenLiquidityPosition",
    outputs: [
      {
        internalType: "bool",
        name: "cancelled",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "closeLiquidityPositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "closeLiquidityPositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "closeLiquidityPositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "positionID",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "receiver",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
        ],
        internalType: "struct IPositionRouter.CloseLiquidityPositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "positionID",
        type: "uint96",
      },
      {
        internalType: "int128",
        name: "marginDelta",
        type: "int128",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "createAdjustLiquidityPositionMargin",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint96",
        name: "positionID",
        type: "uint96",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "createCloseLiquidityPosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "Side",
        name: "side",
        type: "uint8",
      },
      {
        internalType: "uint128",
        name: "marginDelta",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "sizeDelta",
        type: "uint128",
      },
      {
        internalType: "uint160",
        name: "acceptableTradePriceX96",
        type: "uint160",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "createDecreasePosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "liquidityDelta",
        type: "uint128",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "createDecreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "Side",
        name: "side",
        type: "uint8",
      },
      {
        internalType: "uint128",
        name: "marginDelta",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "sizeDelta",
        type: "uint128",
      },
      {
        internalType: "uint160",
        name: "acceptableTradePriceX96",
        type: "uint160",
      },
    ],
    name: "createIncreasePosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "liquidityDelta",
        type: "uint128",
      },
    ],
    name: "createIncreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "margin",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
    ],
    name: "createOpenLiquidityPosition",
    outputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "decreasePositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decreasePositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "decreasePositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "marginDelta",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "sizeDelta",
            type: "uint128",
          },
          {
            internalType: "uint160",
            name: "acceptableTradePriceX96",
            type: "uint160",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "Side",
            name: "side",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "receiver",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType: "struct IPositionRouter.DecreasePositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decreaseRiskBufferFundPositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decreaseRiskBufferFundPositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "decreaseRiskBufferFundPositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "liquidityDelta",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "receiver",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType:
          "struct IPositionRouter.DecreaseRiskBufferFundPositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeAdjustLiquidityPositionMargin",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeAdjustLiquidityPositionMargins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeCloseLiquidityPosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeCloseLiquidityPositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeDecreasePosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeDecreasePositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeDecreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeDecreaseRiskBufferFundPositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeIncreasePosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeIncreasePositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeIncreaseRiskBufferFundPosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeIncreaseRiskBufferFundPositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeOpenLiquidityPosition",
    outputs: [
      {
        internalType: "bool",
        name: "executed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "endIndex",
        type: "uint128",
      },
      {
        internalType: "address payable",
        name: "executionFeeReceiver",
        type: "address",
      },
    ],
    name: "executeOpenLiquidityPositions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "increasePositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "increasePositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "increasePositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "marginDelta",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "sizeDelta",
            type: "uint128",
          },
          {
            internalType: "uint160",
            name: "acceptableTradePriceX96",
            type: "uint160",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "Side",
            name: "side",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType: "struct IPositionRouter.IncreasePositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "increaseRiskBufferFundPositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "increaseRiskBufferFundPositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "increaseRiskBufferFundPositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "liquidityDelta",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType:
          "struct IPositionRouter.IncreaseRiskBufferFundPositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "openLiquidityPositionIndex",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "openLiquidityPositionIndexNext",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "index",
        type: "uint128",
      },
    ],
    name: "openLiquidityPositionRequests",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "blockNumber",
            type: "uint96",
          },
          {
            internalType: "contract IPool",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "blockTime",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "margin",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "executionFee",
            type: "uint256",
          },
        ],
        internalType: "struct IPositionRouter.OpenLiquidityPositionRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "minBlockDelayExecutor",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "minTimeDelayPublic",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "maxTimeDelay",
        type: "uint32",
      },
    ],
    name: "updateDelayValues",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint160",
        name: "executionGasLimit",
        type: "uint160",
      },
    ],
    name: "updateExecutionGasLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "minExecutionFee",
        type: "uint256",
      },
    ],
    name: "updateMinExecutionFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "updatePositionExecutor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPositionRouterState__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionRouterStateInterface {
    return new utils.Interface(_abi) as IPositionRouterStateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPositionRouterState {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPositionRouterState;
  }
}
